name: mindtale

services:
  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file: ./backend/.env
    networks:
      - mindtale
    expose:
      - "3001" # Internal API port

  frontend:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: /backend
    restart: unless-stopped
    networks:
      - mindtale
    depends_on:
      - api
    expose:
      - "5173" # Internal Frontend port

networks:
  mindtale:
    driver: bridge
