name: mindtale

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mindtale
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - mindtale
    depends_on:
      - api
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mindtale
    depends_on:
      - api
      - frontend

volumes:
  caddy_data:
  caddy_config:

networks:
  mindtale:
    driver: bridge
