name: mindtale

services:
  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file: ./backend/.env
    networks:
      - mindtale
  frontend:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - mindtale
    depends_on:
      - api
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - mindtale
    depends_on:
      - api
      - frontend

volumes:
  caddy_data:
  caddy_config:

networks:
  mindtale:
    driver: bridge
