export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
