export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const VERIFY_FAIL = "VERIFY_FAIL";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_RANKING_SUCCESS = "GET_RANKING_SUCCESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const CHECK_VERIFICATION_CODE_SUCCESS =
  "CHECK_VERIFICATION_CODE_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const GET_STORIES_STATS_SUCCESS = "GET_STORIES_STATS_SUCCESS";

export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";

export const READ_STORY_SUCCESS = "READ_STORY_SUCCESS";
export const SUBMIT_USER_CHOICE_SUCCESS = "SUBMIT_USER_CHOICE_SUCCESS";
export const GET_ASSESMENT_SUCCESS = "GET_ASSESMENT_SUCCESS";
export const GENERATE_COVER_SUCCESS = "GENERATE_COVER_SUCCESS";
export const ADD_STORY_SUCCESS = "ADD_STORY_SUCCESS";
export const TRANSLATE_TEXT_SUCCESS = "TRANSLATE_TEXT_SUCCESS";
export const RESET_SESSION = "RESET_SESSION";
