export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";

export const READ_STORY_SUCCESS = "READ_STORY_SUCCESS";
export const SUBMIT_USER_CHOICE_SUCCESS = "SUBMIT_USER_CHOICE_SUCCESS";
